version: 2

jobs:
  setup:
    docker:
      - image: circleci/node:10.16.1

    working_directory: ~/elm

    steps:
      - checkout

      - restore_cache:
          keys:
          - elm-0.19-node_modules-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: elm-0.19-node_modules-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths: ./*

  lint:
    docker:
      - image: circleci/node:10.16.1

    working_directory: ~/elm

    steps:
      - attach_workspace:
          at: ~/

      - restore_cache:
          keys:
          - elm-0.19-dependencies-{{ checksum "elm.json" }}

      - run: npm run prettify

      - save_cache:
          paths:
            - elm-stuff
            - ~/.elm
          key: elm-0.19-dependencies-{{ checksum "elm.json" }}

      - persist_to_workspace:
          root: ~/
          paths: ./*

  test:
    docker:
      - image: circleci/node:10.16.1

    working_directory: ~/elm

    steps:
      - attach_workspace:
          at: ~/

      - restore_cache:
          keys:
          - elm-0.19-dependencies-{{ checksum "elm.json" }}

      - run: npm run test

      - save_cache:
          paths:
            - elm-stuff
            - ~/.elm
          key: elm-0.19-dependencies-{{ checksum "elm.json" }}

      - persist_to_workspace:
          root: ~/
          paths: ./*

  build:
    docker:
      - image: circleci/node:10.16.1

    working_directory: ~/elm

    steps:
      - attach_workspace:
          at: ~/

      - run: npm run build

  build-production:
    docker:
      - image: circleci/node:10.16.1

    working_directory: ~/elm

    steps:
      - attach_workspace:
          at: ~/

      - run: npm run build:production

      - persist_to_workspace:
          root: ~/
          paths: ./*

  deploy:
    docker:
      - image: circleci/node:10.16.1

    working_directory: ~/elm

    steps:
      - attach_workspace:
          at: ~/

      - run: git config --global user.name "Marei Kikukawa"
      - run: git config --global user.email "contact@marei.jp"
      - run: npm run deploy

workflows:
  version: 2

  lint-test-build-and-deploy:
    jobs:
      - setup

      - lint:
          requires:
            - setup

      - test:
          requires:
            - lint

      - build:
          requires:
            - test

      - build-production:
          requires:
            - test

      - deploy:
          requires:
            - build
            - build-production

          filters:
            branches:
              only: master
